// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package housekeeper_mocks is a generated GoMock package.
package housekeeper_mocks

import (
	housekeeper "booking-svc/pkg/repositories/housekeeper"
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// PickAvailableHouseKeeper mocks base method.
func (m *MockRepository) PickAvailableHouseKeeper(c context.Context, bookingPrice float64, bookingDate time.Time) (housekeeper.HouseKeeper, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PickAvailableHouseKeeper", c, bookingPrice, bookingDate)
	ret0, _ := ret[0].(housekeeper.HouseKeeper)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PickAvailableHouseKeeper indicates an expected call of PickAvailableHouseKeeper.
func (mr *MockRepositoryMockRecorder) PickAvailableHouseKeeper(c, bookingPrice, bookingDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PickAvailableHouseKeeper", reflect.TypeOf((*MockRepository)(nil).PickAvailableHouseKeeper), c, bookingPrice, bookingDate)
}
