// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package job_mocks is a generated GoMock package.
package job_mocks

import (
	job "booking-svc/pkg/repositories/job"
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AssignHouseKeeperToJob mocks base method.
func (m *MockRepository) AssignHouseKeeperToJob(c context.Context, jobID string, bookingPrice float64, houseKeeperInfo job.HouseKeeperInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignHouseKeeperToJob", c, jobID, bookingPrice, houseKeeperInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignHouseKeeperToJob indicates an expected call of AssignHouseKeeperToJob.
func (mr *MockRepositoryMockRecorder) AssignHouseKeeperToJob(c, jobID, bookingPrice, houseKeeperInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignHouseKeeperToJob", reflect.TypeOf((*MockRepository)(nil).AssignHouseKeeperToJob), c, jobID, bookingPrice, houseKeeperInfo)
}

// InitJob mocks base method.
func (m *MockRepository) InitJob(c context.Context, clientInfo job.ClientInfo, bookingDate time.Time) (job.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitJob", c, clientInfo, bookingDate)
	ret0, _ := ret[0].(job.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitJob indicates an expected call of InitJob.
func (mr *MockRepositoryMockRecorder) InitJob(c, clientInfo, bookingDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitJob", reflect.TypeOf((*MockRepository)(nil).InitJob), c, clientInfo, bookingDate)
}
